### ISSUE TITLE
Branch Coverage for CompareHands.compareHands()

### ISSUE THREAD

**Issue by zachariaserlandsson** [dackebro/cs56-games-poker#3]
Identify all branches in the given functions; assign a unique number (ID) to each one.
Before the program starts (before the first instruction in "main" or as the first step in the unit test harness), create data structures that hold coverage information about specific branches.
Before the first statement of each branch outcome (including to-be-added "else" clauses if none exist), add a line that sets a flag if the branch is reached.
At the end of the program (as the last instruction in "main" or at the end of all unit tests), write all information about the taken branches taken to a file or console.

**Comment by ghost** [comment]
[Flow chart](https://ibb.co/ihrUvx)
**Path list (12 paths)**
- compareHands1 = A,B,B1
- compareHands2 = A,B,C,C1
- compareHands3 = A,B,C,D,D1
- compareHands4 = A,B,C,D,E,E1
- compareHands5 = A,B,C,D,E,F,F1
- compareHands6 = A,B,C,D,E,F,G,G1
- compareHands7 = A,B,C,D,E,F,G,H,H1
- compareHands8 = A,B,C,D,E,F,G,H,I,I1
- compareHands9 = A,B,C,D,E,F,G,H,I,J,J1
- compareHands10 = A,B,C,D,E,F,G,H,I,J,K,K1
- compareHands11 = A,B,C,D,E,F,G,H,I,J,K,L, L1
- compareHands12 = A,B,C,D,E,F,G,H,I,J,K,L, M
